apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth-microservice:v1
          ports:
            - containerPort: 3000
