apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
        - name: patient
          image: patient-microservice:v1
          ports:
            - containerPort: 3002
