apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: microservices
spec:
  selector:
    app: patient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002
  type: NodePort
