apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-deployment
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
        - name: doctor
          image: doctor-microservice:v1
          ports:
            - containerPort: 3001
