apiVersion: v1
kind: Service
metadata:
  name: doctor-service
  namespace: microservices
spec:
  selector:
    app: doctor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: NodePort
