name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, doctor, patient]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      # Paso para instalar dependencias y ejecutar pruebas aquí, si es necesario

      - name: Build Docker image
        run: |
          docker build -t gomezdeltoroagustin/${{ matrix.service }}-microservice:${{ github.sha }} ./${{ matrix.service }}-microservice

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: |
          docker push gomezdeltoroagustin/${{ matrix.service }}-microservice:${{ github.sha }}

      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      - name: Apply Kubernetes files
        run: |
          kubectl set image deployment/${{ matrix.service }}-deployment ${{ matrix.service }}=gomezdeltoroagustin/${{ matrix.service }}-microservice:${{ github.sha }} -n microservices